### PR TITLE
It's just Angular

### PR DESCRIPTION
**Pull request by sarunint**

### CODE REVIEW

**Comment by stevenkampen** [comment]
@sarunint There are a few more instances of "Angular 2" in this repo. Let me add onto your PR and then we will merge it.

**Comment by stevenkampen** [comment]
resolves #1046

**Comment by sarunint** [comment]
@stevenkampen I now believe that all instances of Angular 2 have been replaced. Please check if I miss something.

**Comment by stevenkampen** [comment]
@sarunint Thank you!

**Pull request merged**
