### PR TITLE
fix #1324 Define selectedComponentProperty in the way it could be redefined

### LINKED ISSUE #1324: TypeError: Cannot redefine property: $$el     at Function.defineProperty (<anonymous>)     at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185     at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)
Augury: 1.19.1
Date: Tue, 31 Jul 2018 03:29:51 GMT
OS: Win64

Description of issue:
-- When selecting a component it throws error :+1: 
 TypeError: Cannot redefine property: $$el
    at Function.defineProperty (<anonymous>)
    at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185
    at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)

Angular version (required): 5

Steps to reproduce:

1. Open Angular app
2. Go to Developer too;
3. Go to Augury select any component.ts file throws error :+1: 

ypeError: Cannot redefine property: $$el
    at Function.defineProperty (<anonymous>)
    at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185
    at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)

### PR DESCRIPTION
**Pull request by TaPO4eg3D**
fixes #1324

### CODE REVIEW

**Comment by yallen011** [comment]
Does an issue already exist for this pr? If so could you please reference the issue, if not could you please create an issue for this pr giving a brief description. Also, specific if it is a breaking change, a fix or an enhancement. 

Thank you for your submission and choosing to contributing to the Augury project.

**Comment by TaPO4eg3D** [comment]
Sorry, it's my first time doing PR. I referenced the issue in the title of PR, should I mention it elsewhere?

**Comment by yallen011** [comment]
Can you send this message in the PR you created. So we can centralize
communication to one place and keep track. Also, your doing great :) I know
doing PRs can be scary and confusing when your first starting out. I'm
learning too :)

**Comment by TaPO4eg3D** [comment]
This PR fixes #1324 
Please review

**Comment by feeloor** [comment]
@TaPO4eg3D There seems to be some conflicts blocking the merge, could you resolve these conflicts? 
Thanks!

**Comment by TaPO4eg3D** [comment]
Done

**Comment by TaPO4eg3D** [comment]
@feeloor Done

**Comment by feeloor** [comment]
Great, thanks for your contributions @TaPO4eg3D!

**Pull request merged**
