### PR TITLE
html update

### PR DESCRIPTION
**Pull request by danielschifano**
This PR updates the HTML across the codebase. The majority of the changes consist of:

- Spacing consistency
- Structure consistency 
- Stacking attributes for readability

### CODE REVIEW

**Comment by sumitarora** [comment]
@danielschifano Is there a way we can enforce these rules moving ahead. Also can you check `popup.html` also for the same.

**Comment by danielschifano** [comment]
@sumitarora @vanessayuenn I think just following a guideline will be fine. We should have a lint-css file though.

**Comment by sumitarora** [comment]
LGTM 💯

**Comment by vanessayuenn** [comment]
LGTM2!

**Pull request merged**
