### PR TITLE
#641 Feature - Select DOM reference 

### PR DESCRIPTION
**Pull request by mobinni**
This feature request refers to issue #641 as requested by @born2net

The feature implementation includes:
- DOM selection linking to augury (onclick selection and onhover highlighting)
- Refactoring to backend.ts to allow window events to be added
- CSS Hot reloading fix (You have to reload your frontend inspector to get the changes)
- Removed duplicate exclude from webpack config
- Updated css loader for speed improvements

Update:
- Added fixes for dark mode 
- Added tab redirect on click of select DOM element. If you're on another tab it will redirect you to component tree. Maybe we could add a check to make sure it's tab 0 ? @sumitarora 

alt tag

### CODE REVIEW

**Comment by born2net** [comment]
Sweeeet... when / how can I test this?

**Comment by mobinni** [comment]
@born2net until it's merged it would be difficult, you could checkout my branch and cut a local build for yourself.

**Comment by born2net** [comment]
ok no worries, I will just wait for release.. please let me know when feature is out in the wild!
tx again!
and since I know u r into ng2, checkout my video ;)

https://www.youtube.com/watch?v=bEkPEnudm7s&feature=youtu.be

it's awesome 

regards

**Comment by mobinni** [comment]
@born2net Hey I just discussed it with my PM and if you go into circle CI once the build is completed you can click on the artifacts tab and download a version of the build!

**Comment by born2net** [comment]
no idea what CI and circle means.. :)
will wait till you release it
TX!

**Comment by mobinni** [comment]
Oh I just meant that if you surf to this url: https://circleci.com/gh/rangle/augury/1484#artifacts/containers/0

You can download the zip that contains the release of augury with this feature.

**Comment by born2net** [comment]
I see tx!

**Comment by born2net** [comment]
I am wondering if this feature has been released to the wild?
regards

Sean

**Comment by mobinni** [comment]
@born2net No, until it's verified and merged it will not be in an "official" build, however you can download the unofficial build from https://circleci.com/gh/rangle/augury/1484#artifacts/containers/0.

Just uninstall your current augury and drag the zi; into chrome://extensions

**Comment by born2net** [comment]
ok did that and I see the new icon with arrow and rec, however when I press on it and select UI in my HTML, nothing happens  ...

regards

**Comment by mobinni** [comment]
@born2net Oh, that shouldn't happen. It should highlight the node in the component tree of augury and you should be able to see the properties change.

Could you possibly supply a sample application in which this occurs?

Regards
Mo Binni

**Comment by born2net** [comment]
sure the project is at:
https://github.com/born2net/studioDashboard
demo user: reseller@ms.com pass: 123123
to use it:

```
git clone https://github.com/born2net/studioDashboard.git
cd studioDashboard
npm install -g jspm@beta
npm install -g gulp
npm install
```

And after further testing, it seems to work 25% of time.
Most of the time (if the UI is more complex, which most of this App has complex UI) the selection does not work... when it does work, it's AWESOME

let me know if you have questions,

regards

Sean

**Comment by mobinni** [comment]
@born2net are you on the augury slack per chance?

Regards 
Mo

**Comment by born2net** [comment]
I can be... but in about an hour or so...

**Comment by mobinni** [comment]
I can't seem to get your project to run and I wanted to try it out, so whenever you could contact me would be cool.

**Comment by born2net** [comment]
I am trying to login to slack now

**Comment by born2net** [comment]
what's the slack URL?

**Comment by mobinni** [comment]
what's your e-mail I'll send you an invite

**Comment by born2net** [comment]
born2net@gmail.com

**Comment by mobinni** [comment]
Waiting on an icon from @amitafr before merging. Please still review

**Comment by stevenkampen** [comment]
@mobinni LGTM

**Comment by stevenkampen** [comment]
@mobinni I've reviewed your latest changes. LGTM.

**Pull request merged**
