### PR TITLE
Replace precomputed providers used to determine injection point

### LINKED ISSUE #1078: "Self-Provided" broken in injector tree
Augury version (required): >1.2.11
Angular version (required): all
Date: (24-04-17)
OS: all

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
https://github.com/johnpapa/angular-event-view-cli (LoginComponent)

Description of issue:
Self provided injectables are not marked as so on the injector tree UI.

Steps to reproduce:
1. View Injector Tree of LoginComponent in above repo.

### PR DESCRIPTION
**Pull request by stevenkampen**
resolves #1078

### CODE REVIEW

**Comment by stevenkampen** [comment]
@AbdellaToronto Can you review this one? It's pretty straight forward. Something was removed that shouldn't have been and silently broke something else.

**Comment by stevenkampen** [comment]
@AbdellaToronto or @riavalon Please review.

**Comment by stevenkampen** [comment]
@JinSY Please review.

**Comment by stevenkampen** [comment]
@igor-ka Please review.

**Comment by stevenkampen** [comment]
@igor-ka Rebased

**Comment by charpeni** [comment]
Can we have a release with this? That would be appreciated.

**Comment by stevenkampen** [comment]
@charpeni Release will happen today. Thanks.

**Pull request merged**
