### PR TITLE
new architecture image

### LINKED ISSUE #824: New architecture diagram

### PR DESCRIPTION
**Pull request by mobinni**
resolves #824

### CODE REVIEW

**Comment by stevenkampen** [comment]
@mobinni do you think it would be helpful to elaborate a little more on the nature of `backend.ts`? Maybe just mentioning that it runs inside the angular application context, and that it also builds the router tree (or maybe just that it does 'things like this').

**Comment by mobinni** [comment]
@stevenkampen good idea! Done :)

**Comment by stevenkampen** [comment]
@mobinni awesome. Can you resize that shape so it doesn't cut the text off?

**Comment by mobinni** [comment]
Fixed! :D

**Comment by stevenkampen** [comment]
@mobinni Great. :shipit: :)

**Pull request merged**
