### PR TITLE
Fix merge conflicts (Release 1.0.5)

### PR DESCRIPTION
**Pull request by ericjim**
I tried merging `dev` into `master`, but my PR was failing due to merge conflicts https://github.com/rangle/augury/pull/514.

In this PR, I've resolved the merge conflicts in a branch that came off `dev`. I would like to bring the fixes back into `dev` before attempting another PR targeting `master`.

Does that make sense? @sumitarora @igor-ka?

### CODE REVIEW

**Comment by sumitarora** [comment]
no files ??

**Comment by ericjim** [comment]
@sumitarora Yeah, that's because no files changed between `dev` and `fix-merge-conflicts`. The only difference is that `fix-merge-conflicts` has a history that `master` was merged into it. By merging `fix-merge-conflicts` into `dev`, we would then be able to merge `dev` into `master`. Does that make sense? Maybe there is a better way?

**Comment by sumitarora** [comment]
@ericjim Can you create PR from this branch to master so I can review it has all the changes and no issues? Just want to be 100% sure

**Comment by ericjim** [comment]
How's that? https://github.com/rangle/augury/pull/521

**Pull request closed without merging**
