### PR TITLE
changing slack status

### PR DESCRIPTION
**Pull request by sumitarora**

### CODE REVIEW

**Comment by bertrandk** [comment]
lgtm. 🐑 🐑 🐑 

Why the `wontfix` label?

**Comment by vanessayuenn** [comment]
i was also wonder why the `wontfix` label was on everything

**Comment by bertrandk** [comment]
It is a novel development strategy. 😉

**Comment by sumitarora** [comment]
I thinks waffle adds it if there is no issue associated with PR

**Pull request merged**
