### PR TITLE
Fix recursive serialization issue that Eric found

### PR DESCRIPTION
**Pull request by clbond**
This issue will not affect any users. But it will produce a nasty exception in the console if you try debugging Augury itself (which I am assuming very few people will)

### CODE REVIEW

**Comment by ericjim** [comment]
Very nice

**Comment by ericjim** [comment]
So in other words, it's not the router tree causing the issue, it was the dev tools, debugging the router tree which raised the exception.

**Comment by clbond** [comment]
No, it was caused by this flow:

* Open an Angular 2 application with Augury closed
* Do some stuff in the application that causes it to rerender itself a couple times
* Open Augury

But there is no way this exception could affect use of the application in any way, because the frontend will request a tree on ngOnInit regardless and the offending message -- getting a diff for a tree that doesn't exist, because Augury wasn't open -- will essentially be discarded.

**Comment by sumitarora** [comment]
:shipit: 🚀

**Pull request merged**
