### PR TITLE
CSS update

### PR DESCRIPTION
**Pull request by danielschifano**
This PR updates the CSS across the codebase. The majority of the changes consist of:

Form Structure
Better Code Readability
CSS best practices
Implementation

This will be the first part of CSS changes. Next tasks would be to reduce bloat and utilize more immutable classes from Basscss.

### CODE REVIEW

**Comment by vanessayuenn** [comment]
LGTM 👍 . @sumitarora ?

**Comment by sumitarora** [comment]
@danielschifano In the `popup.html` I am seeing extra underline.
screen shot 2016-05-16 at 9 02 04 am

**Comment by danielschifano** [comment]
@sumitarora fixed and updated.

**Comment by sumitarora** [comment]
🚢

**Pull request merged**
