### PR TITLE
adding logo back in header

### LINKED ISSUE #664: Regression: Add Augury Logo back
Should bring back Augury logo to the top left corner of the view, i.e. left of the Component Tree tab.

### PR DESCRIPTION
**Pull request by sumitarora**
Should resolve #664

image

### CODE REVIEW

**Comment by igor-ka** [comment]
Hey @sumitarora looks good overall, the only thing is that i would adjust the padding (or whatever) to position it evenly between the first tab on the right and the dev tools viewport border on the left.
screen shot 2016-09-15 at 10 07 59 am

**Comment by igor-ka** [comment]
@sumitarora also the logo appears in 2 places like in the screenshot below...

screen shot 2016-09-15 at 10 56 34 am

**Comment by xorgy** [comment]
@sumitarora Take a look at how I got the settings button into the top tab bar, should be a similar procedure. (Except you'll want the transclusion slot for the logo to be inside the tab container, rather than outside).

**Comment by sumitarora** [comment]
@xorgy I had to do it using flag `showLogo` due to issue in transclusion that content is rendered after initial content always here is the issue related to that https://github.com/angular/angular/issues/6164

**Comment by igor-ka** [comment]
@sumitarora nice! LGTM :shipit:

**Pull request merged**
