### PR TITLE
Reduce unnecessary imports

### LINKED ISSUE #782: Get rid of @angular/core as a dependency on the backend

### PR DESCRIPTION
**Pull request by stevenkampen**
resolves #782

### CODE REVIEW

**Comment by mobinni** [comment]
Augury does not load correctly after this change, I downloaded the crx and imported it and when loading augury I get the following error:
```
Unhandled Promise rejection: subject.debounceTime is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: subject.debounceTime is not a function(…) TypeError: subject.debounceTime is not a function
    at bind (chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8863:33)
    at chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8885:71
    at Array.forEach (native)
    at chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8885:38
    at checkDebug (chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8874:10)
    at resubscribe (chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8879:6)
    at chrome-extension://coffiajmcbcnckbcakciiafcmgpblnaa/build/backend.js:8888:94
    at ZoneDelegate.invoke (http://localhost:8080/vendor.9045b0a28c3ea5f8a3d4.bundle.js:61910:27)
    at Zone.run (http://localhost:8080/vendor.9045b0a28c3ea5f8a3d4.bundle.js:61792:44)
    at http://localhost:8080/vendor.9045b0a28c3ea5f8a3d4.bundle.js:62180:58consoleError @ zone.js:388_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421ZoneTask.invoke @ zone.js:339
zone.js:390 Error: Uncaught (in promise): TypeError: subject.debounceTime is not a function(…)
```

**Comment by stevenkampen** [comment]
@mobinni Thanks mate. I think that's a result of the merged in changes. Should be easy to sort out.

**Comment by stevenkampen** [comment]
@mobinni Ok that fixes it.

**Comment by mobinni** [comment]
LGTM 🚀

**Pull request merged**
