### PR TITLE
FireFox compatibility using WebExtensions format.

### PR DESCRIPTION
**Pull request by santiago-elustondo**
issue: https://github.com/rangle/augury/issues/1150

### CODE REVIEW

**Comment by santiago-elustondo** [comment]
todo at this point:
- Mozilla verification required.
- manifest.require_url is not supported by Mozilla, and is giving an error when loading plugin (it does not prevent plugin from loading, however)

**Comment by santiago-elustondo** [comment]
no outstanding manifest questions

**Comment by potch** [comment]
Hello! I'm Potch, from Mozilla dev advocacy.

I built this branch locally and loaded the extension into Firefox to test it out. It seems to be working, but do you have any specific test apps I can point it at to verify?

Thanks for putting in the leg-work to port!

**Comment by sumitarora** [comment]
@potch You can test any of the Angular 2+ applications. We use this as the base application to check https://github.com/rangle/augury-examples/tree/master/kitchen-sink-demo If you want to check just run the application and test it in Firefox :D

**Comment by potch** [comment]
I wasn't able to get the kitchen-sink-demo to build, but tried it on https://angular-quickstart.glitch.me/ and got the expected panel and was able to browse the (admittedly tiny) component tree. Excited to see this working!

**Comment by abdulkareemnalband** [comment]
What is the status of this PR?

**Comment by andrewthauer** [comment]
We are currently working to get Augury approved in the Firefox add-on store. We hit a small issue with the add-on size which is [being investigated](https://github.com/mozilla/addons/issues/662). In the short-term you could pull the PR branch, build the add-on, then install the add-on from a file.

**Comment by digitarald** [comment]
@andrewthauer it looks like the [referenced AMO issue](https://github.com/mozilla/addons/issues/662) will not be fixed soon (as not many extensions are known to be blocked by this, so it is hard to make weigh risks vs benefits; working on it). Are you waiting on this or are you still working on splitting/reducing JS bundle size?

**Comment by andrewthauer** [comment]
@digitarald we are good now. We were able to get the bundle size down and I was able to successfully submit the add-on. Just a few final tweaks and it should be ready to go very soon.

Thanks for following up. Looks like the AMO issue can be closed. Anything else you can think of that we should look at or do before publishing?

**Comment by digitarald** [comment]
@andrewthauer looks like you submitted? Did it all work out?

**Comment by digitarald** [comment]
Our review process is a little more involved, hopefully it doesn’t cause too much extra work. If anything is unclear, you can ask the reviewers by replying to the review email. Feel free to loop me in as needed.

**Comment by andrewthauer** [comment]
Thanks @digitarald! I've followed up with some additional questions for the reviewer. I'll reach out to you if we run into any problems.

**Pull request merged**
