### PR TITLE
Add "expand all" (Cmd-Click or Ctrl-Click) and "collapse all" (Alt-Click) functionality

### LINKED ISSUE #629: Add ability to expand all and collapse all through Cmd/Ctrl-Click (expand) and Alt-Click (collapse)
In the component tree, the user should be able to expand all nodes (Cmd-Click or Ctrl-Click) or collapse all nodes (Alt-Click). Addressed in https://github.com/rangle/augury/pull/627

### PR DESCRIPTION
**Pull request by clbond**
This resolves #629

### CODE REVIEW

**Comment by clbond** [comment]
Added collapse all in addition to expand all

**Comment by igor-ka** [comment]
@clbond LGTM but first let's create an issue for this with a description of the feature. I'll give it the approval after

**Comment by clbond** [comment]
https://github.com/rangle/augury/issues/629

**Comment by xorgy** [comment]
:shipit:

**Comment by igor-ka** [comment]
:shipit:

**Pull request merged**
